[package]
name        = "snap7-sys"
version     = "0.1.0"
authors     = ["hal-rs initiative"]
license     = "MIT"
description = "Rust bindings to snap7 library"
repository  = "https://github.com/hal-rs/snap7"
categories  = ["HAL", "PLC", "Siemens S7"]

build       = "build.rs"

[build-dependencies]
bindgen = "*"

[dependencies]
libc = "0.2"

#[[example]]
#name = "simple"
